"""baseline schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_series",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("units", sa.String(length=128), nullable=True),
        sa.Column("frequency", sa.String(length=16), nullable=True),
        sa.Column("seasonal_adjustment", sa.String(length=16), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "financial_facts",
        sa.Column("cik", sa.Integer(), nullable=False),
        sa.Column("taxonomy", sa.String(length=32), nullable=False),
        sa.Column("concept", sa.String(length=256), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("instant", sa.Boolean(), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_period", sa.String(length=8), nullable=True),
        sa.Column("filing_fiscal_year", sa.Integer(), nullable=True),
        sa.Column("filing_fiscal_period", sa.String(length=8), nullable=True),
        sa.Column("form", sa.String(length=16), nullable=True),
        sa.Column("filed", sa.Date(), nullable=True),
        sa.Column("frame", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint(
            "cik", "taxonomy", "concept", "unit", "period_start", "period_end", "accession"
        ),
    )
    with op.batch_alter_table("financial_facts", schema=None) as batch_op:
        batch_op.create_index("ix_facts_cik_concept", ["cik", "concept"], unique=False)

    op.create_table(
        "securities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("cik", sa.Integer(), nullable=True),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_securities_cik"), ["cik"], unique=False)

    op.create_table(
        "daily_bars",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("adj_open", sa.Float(), nullable=True),
        sa.Column("adj_high", sa.Float(), nullable=True),
        sa.Column("adj_low", sa.Float(), nullable=True),
        sa.Column("adj_close", sa.Float(), nullable=True),
        sa.Column("adj_volume", sa.BigInteger(), nullable=True),
        sa.Column("dividend", sa.Float(), nullable=False),
        sa.Column("split_factor", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "date", "source"),
    )
    op.create_table(
        "economic_observations",
        sa.Column("series_id", sa.String(length=64), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["economic_series.id"],
        ),
        sa.PrimaryKeyConstraint("series_id", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("economic_observations")
    op.drop_table("daily_bars")
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_securities_cik"))

    op.drop_table("securities")
    with op.batch_alter_table("financial_facts", schema=None) as batch_op:
        batch_op.drop_index("ix_facts_cik_concept")

    op.drop_table("financial_facts")
    op.drop_table("economic_series")
    # ### end Alembic commands ###
