"""ticker history

Revision ID: 0002
Revises: 0001
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_history",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=32), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "ticker"),
    )
    with op.batch_alter_table("ticker_history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticker_history_ticker"), ["ticker"], unique=False)

    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), server_default=sa.true(), nullable=False)
        )
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(length=32), nullable=True)

    # ### end Alembic commands ###
    # Every existing security has been seen under its current ticker.
    op.execute(
        "INSERT INTO ticker_history (security_id, ticker, first_seen, last_seen) "
        "SELECT id, ticker, CURRENT_DATE, CURRENT_DATE FROM securities WHERE ticker IS NOT NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(length=32), nullable=False)
        batch_op.drop_column("active")

    with op.batch_alter_table("ticker_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ticker_history_ticker"))

    op.drop_table("ticker_history")
    # ### end Alembic commands ###
