"""security types and identifiers

Revision ID: 0004
Revises: 0003
"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("origin", sa.String(length=16), server_default="sec", nullable=False)
        )
        batch_op.add_column(sa.Column("mic", sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column("security_type", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("share_class_figi", sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f("ix_securities_figi"), ["figi"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_securities_security_type"), ["security_type"], unique=False
        )

    # ### end Alembic commands ###
    # Until now securities came from SEC's list, or from Tiingo metadata (no CIK).
    op.execute("UPDATE securities SET origin = 'tiingo' WHERE cik IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_securities_security_type"))
        batch_op.drop_index(batch_op.f("ix_securities_figi"))
        batch_op.drop_column("share_class_figi")
        batch_op.drop_column("security_type")
        batch_op.drop_column("mic")
        batch_op.drop_column("origin")

    # ### end Alembic commands ###
