"""market breadth

Revision ID: 0007
Revises: 0006
"""

import sqlalchemy as sa
from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_breadth",
        sa.Column("universe", sa.String(length=32), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("advancers", sa.Integer(), nullable=False),
        sa.Column("decliners", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("ad_line", sa.Integer(), nullable=False),
        sa.Column("up_volume", sa.Double(), nullable=False),
        sa.Column("down_volume", sa.Double(), nullable=False),
        sa.Column("new_highs", sa.Integer(), nullable=False),
        sa.Column("new_lows", sa.Integer(), nullable=False),
        sa.Column("eligible_252", sa.Integer(), nullable=False),
        sa.Column("above_50d", sa.Integer(), nullable=False),
        sa.Column("eligible_50d", sa.Integer(), nullable=False),
        sa.Column("above_200d", sa.Integer(), nullable=False),
        sa.Column("eligible_200d", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("universe", "date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("market_breadth")
    # ### end Alembic commands ###
