"""delisted securities

Revision ID: 0008
Revises: 0007
"""

import sqlalchemy as sa
from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("delisted_on", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_column("delisted_on")

    # ### end Alembic commands ###
