"""company metrics

Revision ID: 0010
Revises: 0009
"""

import sqlalchemy as sa
from alembic import op

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_metrics",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("enterprise_value", sa.Float(), nullable=True),
        sa.Column("revenue_ttm", sa.Float(), nullable=True),
        sa.Column("net_income_ttm", sa.Float(), nullable=True),
        sa.Column("ebit_ttm", sa.Float(), nullable=True),
        sa.Column("fcf_ttm", sa.Float(), nullable=True),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("ev_ebit", sa.Float(), nullable=True),
        sa.Column("ev_ebitda", sa.Float(), nullable=True),
        sa.Column("ev_sales", sa.Float(), nullable=True),
        sa.Column("p_fcf", sa.Float(), nullable=True),
        sa.Column("p_b", sa.Float(), nullable=True),
        sa.Column("earnings_yield", sa.Float(), nullable=True),
        sa.Column("fcf_yield", sa.Float(), nullable=True),
        sa.Column("dividend_yield", sa.Float(), nullable=True),
        sa.Column("shareholder_yield", sa.Float(), nullable=True),
        sa.Column("gross_margin", sa.Float(), nullable=True),
        sa.Column("operating_margin", sa.Float(), nullable=True),
        sa.Column("net_margin", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("roic", sa.Float(), nullable=True),
        sa.Column("debt_to_equity", sa.Float(), nullable=True),
        sa.Column("net_debt_to_ebitda", sa.Float(), nullable=True),
        sa.Column("current_ratio", sa.Float(), nullable=True),
        sa.Column("interest_coverage", sa.Float(), nullable=True),
        sa.Column("revenue_growth", sa.Float(), nullable=True),
        sa.Column("earnings_growth", sa.Float(), nullable=True),
        sa.Column("ebit_growth", sa.Float(), nullable=True),
        sa.Column("operating_margin_5y", sa.Float(), nullable=True),
        sa.Column("operating_margin_vs_5y", sa.Float(), nullable=True),
        sa.Column("altman_z", sa.Float(), nullable=True),
        sa.Column("piotroski_f", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cik"],
            ["issuers.cik"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "as_of"),
    )
    with op.batch_alter_table("company_metrics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_company_metrics_as_of"), ["as_of"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_metrics_as_of"))

    op.drop_table("company_metrics")
    # ### end Alembic commands ###
