"""statement items derived flag

Revision ID: 0011
Revises: 0010
"""

import sqlalchemy as sa
from alembic import op

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("statement_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("derived", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("statement_items", schema=None) as batch_op:
        batch_op.drop_column("derived")

    # ### end Alembic commands ###
