"""insider transactions

Revision ID: 0012
Revises: 0011
"""

import sqlalchemy as sa
from alembic import op

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "insider_transactions",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("form_type", sa.String(length=8), nullable=True),
        sa.Column("filing_date", sa.Date(), nullable=True),
        sa.Column("issuer_cik", sa.Integer(), nullable=False),
        sa.Column("issuer_symbol", sa.String(length=32), nullable=True),
        sa.Column("owner_cik", sa.Integer(), nullable=True),
        sa.Column("owner_name", sa.String(length=256), nullable=True),
        sa.Column("relationship", sa.String(length=64), nullable=True),
        sa.Column("owner_title", sa.String(length=256), nullable=True),
        sa.Column("security_title", sa.String(length=256), nullable=True),
        sa.Column("trans_date", sa.Date(), nullable=False),
        sa.Column("trans_code", sa.String(length=4), nullable=True),
        sa.Column("acquired_disposed", sa.String(length=2), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("shares_after", sa.Float(), nullable=True),
        sa.Column("direct_indirect", sa.String(length=2), nullable=True),
        sa.Column("plan_10b5_1", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("insider_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_insider_transactions_accession"), ["accession"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_insider_transactions_filing_date"), ["filing_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_insider_transactions_issuer_cik"), ["issuer_cik"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_insider_transactions_trans_date"), ["trans_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("insider_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insider_transactions_trans_date"))
        batch_op.drop_index(batch_op.f("ix_insider_transactions_issuer_cik"))
        batch_op.drop_index(batch_op.f("ix_insider_transactions_filing_date"))
        batch_op.drop_index(batch_op.f("ix_insider_transactions_accession"))

    op.drop_table("insider_transactions")
    # ### end Alembic commands ###
