"""institutional holdings

Revision ID: 0013
Revises: 0012
"""

import sqlalchemy as sa
from alembic import op

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutional_filers",
        sa.Column("cik", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("cik"),
    )
    with op.batch_alter_table("institutional_filers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_institutional_filers_name"), ["name"], unique=False)

    op.create_table(
        "institutional_positions",
        sa.Column("filer_cik", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("cusip", sa.String(length=9), nullable=False),
        sa.Column("put_call", sa.String(length=4), nullable=False),
        sa.Column("issuer_name", sa.String(length=256), nullable=True),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("share_type", sa.String(length=4), nullable=True),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("filed", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["filer_cik"],
            ["institutional_filers.cik"],
        ),
        sa.PrimaryKeyConstraint("filer_cik", "period", "cusip", "put_call"),
    )
    with op.batch_alter_table("institutional_positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_institutional_positions_cusip"), ["cusip"], unique=False
        )

    op.create_table(
        "cusip_mappings",
        sa.Column("cusip", sa.String(length=9), nullable=False),
        sa.Column("figi", sa.String(length=12), nullable=True),
        sa.Column("composite_figi", sa.String(length=12), nullable=True),
        sa.Column("ticker", sa.String(length=32), nullable=True),
        sa.Column("security_type", sa.String(length=64), nullable=True),
        sa.Column("security_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("cusip"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cusip_mappings")
    with op.batch_alter_table("institutional_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_institutional_positions_cusip"))

    op.drop_table("institutional_positions")
    with op.batch_alter_table("institutional_filers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_institutional_filers_name"))

    op.drop_table("institutional_filers")
    # ### end Alembic commands ###
