"""congress trades

Revision ID: 0014
Revises: 0013
"""

import sqlalchemy as sa
from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "congress_reports",
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("chamber", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("state", sa.String(length=8), nullable=True),
        sa.Column("filed", sa.Date(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("electronic", sa.Boolean(), nullable=False),
        sa.Column("transactions", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    with op.batch_alter_table("congress_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_congress_reports_filed"), ["filed"], unique=False)
        batch_op.create_index(batch_op.f("ix_congress_reports_name"), ["name"], unique=False)

    op.create_table(
        "congress_trades",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("chamber", sa.String(length=8), nullable=False),
        sa.Column("owner", sa.String(length=16), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=True),
        sa.Column("asset_name", sa.String(length=256), nullable=True),
        sa.Column("asset_type", sa.String(length=64), nullable=True),
        sa.Column("trans_type", sa.String(length=16), nullable=True),
        sa.Column("trans_date", sa.Date(), nullable=False),
        sa.Column("notified", sa.Date(), nullable=True),
        sa.Column("amount_min", sa.Float(), nullable=True),
        sa.Column("amount_max", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("congress_trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_congress_trades_doc_id"), ["doc_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_congress_trades_ticker"), ["ticker"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_congress_trades_trans_date"), ["trans_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("congress_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_congress_trades_trans_date"))
        batch_op.drop_index(batch_op.f("ix_congress_trades_ticker"))
        batch_op.drop_index(batch_op.f("ix_congress_trades_doc_id"))

    op.drop_table("congress_trades")
    with op.batch_alter_table("congress_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_congress_reports_name"))
        batch_op.drop_index(batch_op.f("ix_congress_reports_filed"))

    op.drop_table("congress_reports")
    # ### end Alembic commands ###
