"""cot positions

Revision ID: 0015
Revises: 0014
"""

import sqlalchemy as sa
from alembic import op

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cot_positions",
        sa.Column("report", sa.String(length=16), nullable=False),
        sa.Column("market_code", sa.String(length=8), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("group", sa.String(length=16), nullable=False),
        sa.Column("market_name", sa.String(length=128), nullable=True),
        sa.Column("open_interest", sa.Float(), nullable=True),
        sa.Column("long", sa.Float(), nullable=True),
        sa.Column("short", sa.Float(), nullable=True),
        sa.Column("spread", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("report", "market_code", "report_date", "group"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cot_positions")
    # ### end Alembic commands ###
