"""economic release calendar

Revision ID: 0016
Revises: 0015
"""

import sqlalchemy as sa
from alembic import op

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "economic_releases",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("link", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "economic_release_dates",
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["economic_releases.id"],
        ),
        sa.PrimaryKeyConstraint("release_id", "date"),
    )
    with op.batch_alter_table("economic_release_dates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_economic_release_dates_date"), ["date"], unique=False)

    with op.batch_alter_table("economic_series", schema=None) as batch_op:
        batch_op.add_column(sa.Column("release_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_economic_series_release_id", "economic_releases", ["release_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("economic_series", schema=None) as batch_op:
        batch_op.drop_constraint("fk_economic_series_release_id", type_="foreignkey")
        batch_op.drop_column("release_id")

    with op.batch_alter_table("economic_release_dates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_economic_release_dates_date"))

    op.drop_table("economic_release_dates")
    op.drop_table("economic_releases")
    # ### end Alembic commands ###
