"""metrics currency

Revision ID: 0017
Revises: 0016
"""

import sqlalchemy as sa
from alembic import op

revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_metrics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("currency", sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("company_metrics", schema=None) as batch_op:
        batch_op.drop_column("currency")

    # ### end Alembic commands ###
