"""listing shares outstanding

Revision ID: 0018
Revises: 0017
"""

import sqlalchemy as sa
from alembic import op

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shares_outstanding", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("shares_as_of", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_column("shares_as_of")
        batch_op.drop_column("shares_outstanding")

    # ### end Alembic commands ###
