"""issuer sic codes

Revision ID: 0019
Revises: 0018
"""

import sqlalchemy as sa
from alembic import op

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sic", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("sic_description", sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column("filer_category", sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f("ix_issuers_sic"), ["sic"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuers_sic"))
        batch_op.drop_column("filer_category")
        batch_op.drop_column("sic_description")
        batch_op.drop_column("sic")

    # ### end Alembic commands ###
