"""statement first filed

Revision ID: 0020
Revises: 0019
"""

import sqlalchemy as sa
from alembic import op

revision = "0020"
down_revision = "0019"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("statement_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_filed", sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("statement_items", schema=None) as batch_op:
        batch_op.drop_column("first_filed")

    # ### end Alembic commands ###
