"""world issuers

Revision ID: 0021
Revises: 0020
"""

import sqlalchemy as sa
from alembic import op

revision = "0021"
down_revision = "0020"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("source", sa.String(length=16), server_default="sec", nullable=False)
        )
        batch_op.add_column(sa.Column("source_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("country", sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column("lei", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("home_ticker", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("fiscal_month", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_issuers_lei"), ["lei"], unique=False)
        batch_op.create_index(batch_op.f("ix_issuers_source_id"), ["source_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuers_source_id"))
        batch_op.drop_index(batch_op.f("ix_issuers_lei"))
        batch_op.drop_column("fiscal_month")
        batch_op.drop_column("home_ticker")
        batch_op.drop_column("lei")
        batch_op.drop_column("country")
        batch_op.drop_column("source_id")
        batch_op.drop_column("source")

    # ### end Alembic commands ###
