"""share class links

Revision ID: 0023
Revises: 0022
"""

import sqlalchemy as sa
from alembic import op

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("share_class_figi", sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column("figi_name", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("isin", sa.String(length=12), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_issuers_share_class_figi"), ["share_class_figi"], unique=False
        )

    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("figi_name", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_column("figi_name")

    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuers_share_class_figi"))
        batch_op.drop_column("isin")
        batch_op.drop_column("figi_name")
        batch_op.drop_column("share_class_figi")

    # ### end Alembic commands ###
