"""issuer same as

Revision ID: 0024
Revises: 0023
"""

import sqlalchemy as sa
from alembic import op

revision = "0024"
down_revision = "0023"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("same_as", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_issuers_same_as"), ["same_as"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("issuers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuers_same_as"))
        batch_op.drop_column("same_as")

    # ### end Alembic commands ###
