"""corporate events

Revision ID: 0025
Revises: 0024
"""

import sqlalchemy as sa
from alembic import op

revision = "0025"
down_revision = "0024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_events",
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("item", sa.String(length=8), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=False),
        sa.Column("form", sa.String(length=24), nullable=False),
        sa.Column("filed", sa.Date(), nullable=False),
        sa.Column("accepted", sa.DateTime(), nullable=True),
        sa.Column("report_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("accession", "item"),
    )
    with op.batch_alter_table("corporate_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_corporate_events_cik"), ["cik"], unique=False)
        batch_op.create_index(batch_op.f("ix_corporate_events_filed"), ["filed"], unique=False)
        batch_op.create_index(batch_op.f("ix_corporate_events_form"), ["form"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("corporate_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corporate_events_form"))
        batch_op.drop_index(batch_op.f("ix_corporate_events_filed"))
        batch_op.drop_index(batch_op.f("ix_corporate_events_cik"))

    op.drop_table("corporate_events")
    # ### end Alembic commands ###
