"""forward outcomes

Revision ID: 0026
Revises: 0025
"""

import sqlalchemy as sa
from alembic import op

revision = "0026"
down_revision = "0025"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forward_outcomes",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=False),
        sa.Column("sector", sa.String(length=16), nullable=True),
        sa.Column("ret_1m", sa.Float(), nullable=True),
        sa.Column("ret_3m", sa.Float(), nullable=True),
        sa.Column("ret_6m", sa.Float(), nullable=True),
        sa.Column("ret_12m", sa.Float(), nullable=True),
        sa.Column("excess_spy_3m", sa.Float(), nullable=True),
        sa.Column("excess_spy_12m", sa.Float(), nullable=True),
        sa.Column("excess_universe_3m", sa.Float(), nullable=True),
        sa.Column("excess_universe_12m", sa.Float(), nullable=True),
        sa.Column("excess_sector_3m", sa.Float(), nullable=True),
        sa.Column("excess_sector_12m", sa.Float(), nullable=True),
        sa.Column("max_drawdown_12m", sa.Float(), nullable=True),
        sa.Column("pe_change_12m", sa.Float(), nullable=True),
        sa.Column("ev_ebit_change_12m", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "as_of"),
    )
    with op.batch_alter_table("forward_outcomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_forward_outcomes_as_of"), ["as_of"], unique=False)
        batch_op.create_index(batch_op.f("ix_forward_outcomes_cik"), ["cik"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forward_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forward_outcomes_cik"))
        batch_op.drop_index(batch_op.f("ix_forward_outcomes_as_of"))

    op.drop_table("forward_outcomes")
    # ### end Alembic commands ###
