"""federal obligations

Revision ID: 0027
Revises: 0026
"""

import sqlalchemy as sa
from alembic import op

revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federal_obligations",
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("naics", sa.String(length=6), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("month", "naics"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("federal_obligations")
    # ### end Alembic commands ###
