"""short interest

Revision ID: 0028
Revises: 0027
"""

import sqlalchemy as sa
from alembic import op

revision = "0028"
down_revision = "0027"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "short_interest",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=False),
        sa.Column("short_position", sa.Float(), nullable=False),
        sa.Column("average_daily_volume", sa.Float(), nullable=True),
        sa.Column("days_to_cover", sa.Float(), nullable=True),
        sa.Column("market", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "settlement_date"),
    )
    with op.batch_alter_table("short_interest", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_short_interest_settlement_date"), ["settlement_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("short_interest", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_short_interest_settlement_date"))

    op.drop_table("short_interest")
    # ### end Alembic commands ###
