"""fund holdings

Revision ID: 0029
Revises: 0028
"""

import sqlalchemy as sa
from alembic import op

revision = "0029"
down_revision = "0028"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_holdings",
        sa.Column("fund", sa.String(length=16), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("identifier", sa.String(length=128), nullable=False),
        sa.Column("series_id", sa.String(length=16), nullable=False),
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("filed", sa.Date(), nullable=False),
        sa.Column("cusip", sa.String(length=9), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("value_usd", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("asset_category", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("fund", "period", "identifier"),
    )
    with op.batch_alter_table("fund_holdings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fund_holdings_cusip"), ["cusip"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund_holdings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fund_holdings_cusip"))

    op.drop_table("fund_holdings")
    # ### end Alembic commands ###
