"""filing texts

Revision ID: 0030
Revises: 0029
"""

import sqlalchemy as sa
from alembic import op

revision = "0030"
down_revision = "0029"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filing_texts",
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column("section", sa.String(length=16), nullable=False),
        sa.Column("cik", sa.Integer(), nullable=False),
        sa.Column("form", sa.String(length=16), nullable=False),
        sa.Column("filed", sa.Date(), nullable=False),
        sa.Column("period", sa.Date(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("accession", "section"),
    )
    with op.batch_alter_table("filing_texts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_filing_texts_cik"), ["cik"], unique=False)
        batch_op.create_index(batch_op.f("ix_filing_texts_filed"), ["filed"], unique=False)

    # ### end Alembic commands ###
    if op.get_bind().dialect.name != "sqlite":
        return  # full-text search is SQLite's FTS5; elsewhere search falls back to LIKE
    # An external-content index over filing_texts.text, kept in sync by triggers.
    op.execute(
        "CREATE VIRTUAL TABLE filing_text_fts USING fts5(text, content='filing_texts', "
        "content_rowid='rowid', tokenize='porter unicode61')"
    )
    op.execute(
        "CREATE TRIGGER filing_texts_ai AFTER INSERT ON filing_texts BEGIN "
        "INSERT INTO filing_text_fts(rowid, text) VALUES (new.rowid, new.text); END"
    )
    op.execute(
        "CREATE TRIGGER filing_texts_ad AFTER DELETE ON filing_texts BEGIN "
        "INSERT INTO filing_text_fts(filing_text_fts, rowid, text) "
        "VALUES ('delete', old.rowid, old.text); END"
    )
    op.execute(
        "CREATE TRIGGER filing_texts_au AFTER UPDATE ON filing_texts BEGIN "
        "INSERT INTO filing_text_fts(filing_text_fts, rowid, text) "
        "VALUES ('delete', old.rowid, old.text); "
        "INSERT INTO filing_text_fts(rowid, text) VALUES (new.rowid, new.text); END"
    )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        for trigger in ("filing_texts_ai", "filing_texts_ad", "filing_texts_au"):
            op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
        op.execute("DROP TABLE IF EXISTS filing_text_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filing_texts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filing_texts_filed"))
        batch_op.drop_index(batch_op.f("ix_filing_texts_cik"))

    op.drop_table("filing_texts")
    # ### end Alembic commands ###
