"""legislators

Revision ID: 0031
Revises: 0030
"""

import sqlalchemy as sa
from alembic import op

revision = "0031"
down_revision = "0030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "committee_memberships",
        sa.Column("committee", sa.String(length=8), nullable=False),
        sa.Column("bioguide", sa.String(length=8), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("side", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("committee", "bioguide"),
    )
    with op.batch_alter_table("committee_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_committee_memberships_bioguide"), ["bioguide"], unique=False
        )

    op.create_table(
        "committees",
        sa.Column("id", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("chamber", sa.String(length=8), nullable=True),
        sa.Column("parent", sa.String(length=8), nullable=True),
        sa.Column("jurisdiction", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "congress_report_members",
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("bioguide", sa.String(length=8), nullable=False),
        sa.Column("party", sa.String(length=32), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    with op.batch_alter_table("congress_report_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_congress_report_members_bioguide"), ["bioguide"], unique=False
        )

    op.create_table(
        "legislator_terms",
        sa.Column("bioguide", sa.String(length=8), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("chamber", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("district", sa.Integer(), nullable=True),
        sa.Column("party", sa.String(length=32), nullable=True),
        sa.Column("first", sa.String(length=64), nullable=True),
        sa.Column("last", sa.String(length=64), nullable=True),
        sa.Column("nickname", sa.String(length=64), nullable=True),
        sa.Column("full_name", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("bioguide", "start"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legislator_terms")
    with op.batch_alter_table("congress_report_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_congress_report_members_bioguide"))

    op.drop_table("congress_report_members")
    op.drop_table("committees")
    with op.batch_alter_table("committee_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_committee_memberships_bioguide"))

    op.drop_table("committee_memberships")
    # ### end Alembic commands ###
