"""lobbying

Revision ID: 0032
Revises: 0031
"""

import sqlalchemy as sa
from alembic import op

revision = "0032"
down_revision = "0031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lobbying_issues",
        sa.Column("filing_uuid", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("entities", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("filing_uuid", "code"),
    )
    with op.batch_alter_table("lobbying_issues", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lobbying_issues_code"), ["code"], unique=False)

    op.create_table(
        "lobbying_reports",
        sa.Column("filing_uuid", sa.String(length=36), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("filing_type", sa.String(length=4), nullable=False),
        sa.Column("registrant_id", sa.Integer(), nullable=True),
        sa.Column("registrant", sa.String(length=256), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("client", sa.String(length=256), nullable=True),
        sa.Column("client_description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("posted", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("filing_uuid"),
    )
    with op.batch_alter_table("lobbying_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lobbying_reports_client"), ["client"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_lobbying_reports_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lobbying_reports_year"), ["year"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lobbying_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lobbying_reports_year"))
        batch_op.drop_index(batch_op.f("ix_lobbying_reports_client_id"))
        batch_op.drop_index(batch_op.f("ix_lobbying_reports_client"))

    op.drop_table("lobbying_reports")
    with op.batch_alter_table("lobbying_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lobbying_issues_code"))

    op.drop_table("lobbying_issues")
    # ### end Alembic commands ###
