"""bills

Revision ID: 0033
Revises: 0032
"""

import sqlalchemy as sa
from alembic import op

revision = "0033"
down_revision = "0032"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_subjects",
        sa.Column("bill_id", sa.String(length=24), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("bill_id", "subject"),
    )
    with op.batch_alter_table("bill_subjects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bill_subjects_subject"), ["subject"], unique=False)

    op.create_table(
        "bills",
        sa.Column("id", sa.String(length=24), nullable=False),
        sa.Column("congress", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("introduced", sa.Date(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("policy_area", sa.String(length=64), nullable=True),
        sa.Column("sponsor", sa.String(length=8), nullable=True),
        sa.Column("sponsor_party", sa.String(length=4), nullable=True),
        sa.Column("cosponsors", sa.Integer(), nullable=True),
        sa.Column("committees", sa.Text(), nullable=True),
        sa.Column("latest_action", sa.Date(), nullable=True),
        sa.Column("latest_action_text", sa.Text(), nullable=True),
        sa.Column("law", sa.String(length=16), nullable=True),
        sa.Column("enacted", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bills_congress"), ["congress"], unique=False)
        batch_op.create_index(batch_op.f("ix_bills_introduced"), ["introduced"], unique=False)
        batch_op.create_index(batch_op.f("ix_bills_policy_area"), ["policy_area"], unique=False)
        batch_op.create_index(batch_op.f("ix_bills_sponsor"), ["sponsor"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bills_sponsor"))
        batch_op.drop_index(batch_op.f("ix_bills_policy_area"))
        batch_op.drop_index(batch_op.f("ix_bills_introduced"))
        batch_op.drop_index(batch_op.f("ix_bills_congress"))

    op.drop_table("bills")
    with op.batch_alter_table("bill_subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bill_subjects_subject"))

    op.drop_table("bill_subjects")
    # ### end Alembic commands ###
