"""presidential documents

Revision ID: 0034
Revises: 0033
"""

import sqlalchemy as sa
from alembic import op

revision = "0034"
down_revision = "0033"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presidential_documents",
        sa.Column("document_number", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("president", sa.String(length=64), nullable=True),
        sa.Column("signed", sa.Date(), nullable=True),
        sa.Column("published", sa.Date(), nullable=True),
        sa.Column("disposition", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("document_number"),
    )
    with op.batch_alter_table("presidential_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_presidential_documents_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_presidential_documents_signed"), ["signed"], unique=False
        )

    op.create_table(
        "presidential_texts",
        sa.Column("document_number", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("document_number"),
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name != "sqlite":
        return
    op.execute(
        "CREATE VIRTUAL TABLE presidential_text_fts USING fts5(text, "
        "content='presidential_texts', content_rowid='rowid', tokenize='porter unicode61')"
    )
    op.execute(
        "CREATE TRIGGER presidential_texts_ai AFTER INSERT ON presidential_texts BEGIN "
        "INSERT INTO presidential_text_fts(rowid, text) VALUES (new.rowid, new.text); END"
    )
    op.execute(
        "CREATE TRIGGER presidential_texts_ad AFTER DELETE ON presidential_texts BEGIN "
        "INSERT INTO presidential_text_fts(presidential_text_fts, rowid, text) "
        "VALUES ('delete', old.rowid, old.text); END"
    )
    op.execute(
        "CREATE TRIGGER presidential_texts_au AFTER UPDATE ON presidential_texts BEGIN "
        "INSERT INTO presidential_text_fts(presidential_text_fts, rowid, text) "
        "VALUES ('delete', old.rowid, old.text); "
        "INSERT INTO presidential_text_fts(rowid, text) VALUES (new.rowid, new.text); END"
    )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        for trigger in ("presidential_texts_ai", "presidential_texts_ad", "presidential_texts_au"):
            op.execute(f"DROP TRIGGER IF EXISTS {trigger}")
        op.execute("DROP TABLE IF EXISTS presidential_text_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presidential_texts")
    with op.batch_alter_table("presidential_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_presidential_documents_signed"))
        batch_op.drop_index(batch_op.f("ix_presidential_documents_kind"))

    op.drop_table("presidential_documents")
    # ### end Alembic commands ###
